x-common-variables: &common-variables
  ELYSIA_PORT: 3000
  EXPRESS_PORT: 3002
  FASTIFY_PORT: 3003
  H3_PORT: 3004
  HATTIP_PORT: 3005
  HONO_PORT: 3006
  ENCORE_PORT: 8080
  ENCORE_LOG: off
  ENCORE_NOTRACE: 1
  ENCORE_RUNTIME_LOG: error

services:
  node:
    build:
      context: ../runtimes/node
      dockerfile: Dockerfile.node
    environment: *common-variables
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://node:3002"]
      interval: 5s
      timeout: 5s
      retries: 5

  bun:
    build:
      context: ../runtimes/bun
      dockerfile: Dockerfile.bun
    environment: *common-variables
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://bun:3002"]
      interval: 5s
      timeout: 5s
      retries: 5

  deno:
    build:
      context: ../runtimes/deno
      dockerfile: Dockerfile.deno
    environment: *common-variables
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://deno:3002"]
      interval: 5s
      timeout: 5s
      retries: 5

  encore:
    image: encorebench
    environment: *common-variables
    networks:
      - bench-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://encore:8080"]
      interval: 5s
      timeout: 5s
      retries: 5

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    environment: *common-variables
    networks:
      - bench-network
    volumes:
      - ../results:/results
    depends_on:
      node:
        condition: service_healthy
      bun:
        condition: service_healthy
      deno:
        condition: service_healthy
      encore:
        condition: service_healthy

networks:
  bench-network:
    driver: bridge
